# Generated by Django 5.0.3 on 2024-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="objet",
            fields=[
                ("id_obj", models.IntegerField(primary_key=True, serialize=False)),
                ("poid_obj", models.IntegerField()),
                ("value_obj", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="sacados",
            fields=[
                ("ids_ac", models.IntegerField(primary_key=True, serialize=False)),
                ("capacity_sac", models.IntegerField()),
            ],
        ),
    ]
